spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/luv2code-library
    username: marcin
    password: marcin
  liquibase:
    change-log: classpath:db/changelog/master.xml
  data:
    rest:
      base-path: /api
okta:
  oauth2:
    client-id: 0oakbvlikiEE3X6SO5d7
    issuer: https://dev-26581089.okta.com/oauth2/default
